postrm: Delete kafka user when uninstalling
Idea from https://github.com/Cdiscount/kafka-debian

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -1,11 +1,25 @@
 #!/bin/sh -e
 
+function remove_user() {
+    USERNAME=$1
+
+    if [ -x "$(command -v deluser)" ]; then
+	grep $USERNAME > /dev/null /etc/passwd && deluser $USERNAME || true
+    else
+	echo >&2 "not deleting $USERNAME system account because deluser command was not found"
+    fi
+}
+
 case "$1" in
     purge)
         rm -rf /var/lib/kafka
         rm -rf /var/log/kafka
+	remove_user 'kafka'
         ;;
-    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    remove|abort-install)
+	remove_user 'kafka'
+	;;
+    upgrade|failed-upgrade|abort-upgrade|disappear)
         ;;
     *)
         echo "postrm called with unknown argument \`$1'" >&2
